use_frameworks!

platform :ios, '9.0'

target 'CirclePay_Example' do
  pod 'CirclePay', :path => '../'

  target 'CirclePay_Tests' do
    inherit! :search_paths
#    pod 'OHHTTPStubs/Swift' , '~> 9.1.0'
  end
end
